openapi: 3.0.0
info:
  description: Runpath users photo album API.
  version: "1.0.0"
  title: Photo Album API
  contact:
    email: michael.mcdowell@hotmail.co.uk
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: users
    description: Operations available to regular users
paths:
  /photos:
    get:
      tags:
        - users
      summary: search users photos
      operationId: searchPhotos
      description: |
        By passing in the appropriate options, you can search for
        available photo information
      parameters:
        - in: query
          name: userId
          description: users photos to return
          required: false
          schema:
            type: integer
        - in: query
          name: albumId
          description: scope photos to this album
          required: false
          schema:
            type: integer
        - in: query
          name: photoId
          description: specfic folder to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/photo'
        '400':
          description: bad input parameter
  
components:
  schemas:
    photo:
      type: object
      required:
        - albumTitle
        - photoTitle
        - url
        - thumbnailUrl
      properties:
        albumTitle:
          type: string
          example: "eaque aut omnis a"
        photoTitle:
          type: string
          example: "quod non quae"
        url:
          type: string
          example: "https://via.placeholder.com/600/9cda61"
        thumbnailUrl:
          type: string
          example: "https://via.placeholder.com/150/9cda61"
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/michael.mcd/Photos.API/1.0.0